[tool.pylint.format]
max-line-length = 120

[tool.pylint.master]
score = false

[tool.pylint.reports]
output-format = "colorized"
disable = ["R0903","C0114","C0115","C0116","W0223","W0511","R0902","R0914","R0912","R0915"]

[tool.ruff]
line-length = 88
target-version = "py314"
